apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: front-deployment
  namespace: demo-ath
  labels:
    app: front 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: periferiafactory/front:v3
        ports:
        - containerPort: 8100
      imagePullSecrets:
      - name: regcred 
--- 
apiVersion: v1 
kind: Service 
metadata:
  name: front-service
  namespace: demo-ath
  labels:
    run: front-service 
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8100
  externalIPs:
  - 172.168.10.52
  selector:
    app: front
