apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: oauth-deployment
  namespace: demo-ath
  labels:
    app: oauth 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
      - name: oauth
        image: periferiafactory/oauth:v2
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred 
--- 
apiVersion: v1 
kind: Service 
metadata:
  name: oauth-service
  namespace: demo-ath
  labels:
    run: oauth-service 
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: oauth
