apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: catalogo-deployment
  namespace: demo-ath
  labels:
    app: catalogo 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalogo
  template:
    metadata:
      labels:
        app: catalogo
    spec:
      containers:
      - name: catalogo
        image: periferiafactory/catalogo:v1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred 
--- 
apiVersion: v1 
kind: Service 
metadata:
  name: catalogo-service
  namespace: demo-ath
  labels:
    run: catalogo-service 
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: catalogo
