apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
  namespace: demo-ath
spec:
  storageClassName: jenkins-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.168.10.51
    path: "/home/jenkins-nfs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-nfs-pvc
  namespace: demo-ath
spec:
  storageClassName: jenkins-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
