apiVersion: v1 
kind: Namespace 
metadata:
  name: demo-ath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: demo-ath
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-ath-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-ath-secret
              key: password
        
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: demo-ath
  labels:
    run: mongodb-service
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongodb
